version: "3.3"

services:
  redis:
    image: redis:latest
    networks:
      - cotabox-net
    ports:
      - "6379:6379"
    restart: on-failure

  mongo:
    image: mongo:latest
    networks:
      - cotabox-net
    ports:
      - "27017:27017"
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - cotabox-net
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

networks:
  cotabox-net:
